name: node-ci-deployment

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Linting with ESLint
        run: npm run lint

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/Dockerfile

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: contains('ref/heads/main', github.ref)
        with:
          username: basileregnault
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push if on main
        uses: docker/build-push-action@v4
        if: contains('ref/heads/main', github.ref)
        with:
          push: true
          context: ./docker/Dockerfile
          tags: basileregnault/ci_cd_node_docker
