name: node-ci-deployment

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - run: docker image build -t nodejs_image ./
      - run: docker run nodejs_image sh -c "npm run lint && npm test && npm run build"

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: basileregnault
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push if pull request
        uses: docker/build-push-action@v4
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
        with:
          push: true
          context: ./
          tags: basileregnault/ci_cd_node_docker:latest
